synse-server/Chart.yaml, synse-server/values.yaml
https://github.com/vapor-ware/synse-server/releases/tag/v2.2.6
=> [synse-server] Update to version 2.2.6

snmp/Chart.yaml, snmp/values.yaml
Update SNMP plugin to version 1.1.1, which updates the plugin to used SDK 1.2
=> [snmp] update app version to 1.1.1

emulator/Chart.yaml, emulator/values.yaml
- Includes release roundup of bug fixes for the 2.4.2 synse-emulator
=> [synse-emulator] - bump to 2.4.2

emulator/Chart.yaml, emulator/values.yaml
- Fix a typo introduced in #23
=> [synse-emulator-plugin] - Bump image to 2.4.2 release

emulator/Chart.yaml, emulator/values.yaml
https://github.com/vapor-ware/synse-emulator-plugin/releases/tag/2.4.5
=> [emulator] update app to version 2.4.5

modbus/Chart.yaml, modbus/values.yaml
https://github.com/vapor-ware/synse-modbus-ip-plugin/releases/tag/1.1.1
=> [modbus] update app to version 1.1.1

emulator/Chart.yaml, emulator/values.yaml
Updated app version supports power devices
=> [emulator] update app to version 2.4.8

emulator/Chart.yaml, emulator/values.yaml
https://github.com/vapor-ware/synse-emulator-plugin/releases/tag/2.4.8
=> [emulator] update app to v2.4.8

synse-server/Chart.yaml, synse-server/values.yaml
https://github.com/vapor-ware/synse-server/releases/tag/v2.2.9
=> [synse-server] update to v2.2.9

emulator/Chart.yaml, emulator/values.yaml
https://github.com/vapor-ware/synse-emulator-plugin/releases/tag/3.0.0-alpha.3
=> [emulator] bump for version 3.0.0-alpha.3

synse-server/Chart.yaml, synse-server/values.yaml
https://github.com/vapor-ware/synse-server/releases/tag/untagged-db27586393ae73ab495f
=> [synse-server] bump for version 3.0.0-alpha.3

emulator/Chart.yaml, emulator/values.yaml
https://github.com/vapor-ware/synse-emulator-plugin/releases/tag/3.0.0-alpha.5
=> [emulator] bump for version 3.0.0-alpha.5

synse-server/Chart.yaml, synse-server/values.yaml
- adds a fix for the `/readcache` streamed responses
- dependency updates
=> [synse-server] bump for v3.0.0-alpha.7

synse-loadgen/.helmignore, synse-loadgen/Chart.yaml, synse-loadgen/README.md, synse-loadgen/templates/NOTES.txt, synse-loadgen/templates/_helpers.tpl, synse-loadgen/templates/configmap.yaml, synse-loadgen/templates/deployment.yaml, synse-loadgen/values.yaml
This PR:
- adds the initial chart for [Synse LoadGen](https://github.com/vapor-ware/synse-loadgen)
=> [synse-loadgen] add chart for Synse LoadGen service

prophetess/Chart.yaml, prophetess/templates/_helpers.tpl, prophetess/templates/configmap.yaml, prophetess/templates/deployment.yaml, prophetess/templates/ingress.yaml, prophetess/templates/service.yaml, prophetess/values.yaml
=> [prophetess] initial chart

emulator/Chart.yaml, emulator/README.md
This PR:
- adds some minor updates to Chart.yaml and README.md, primarily for consistency.
=> [emulator] minor updates for consistency

snmp/Chart.yaml, snmp/values.yaml
Partial fix for https://github.com/vapor-ware/edge-ops/issues/47
=> Image version to 1.2 from 1.1.1.

snmp/Chart.yaml, snmp/README.md, snmp/templates/NOTES.txt, snmp/templates/_helpers.tpl, snmp/templates/configmap.yaml, snmp/templates/deployment.yaml, snmp/templates/service.yaml, snmp/values.yaml
This PR:
- updates the SNMP chart definitions, allowing it to be more flexible/configurable and better documented
~Some of the changes here are specific for the v3 version of the SNMP image, so I'm opening this as a draft for initial review. Once v3 lands, this PR can be converted into a regular PR.~
https://github.com/vapor-ware/synse-snmp-plugin/releases/tag/3.0.0-alpha.1
=> [snmp] chart improvements and updates for v3 plugin

synse-loadgen/Chart.yaml, synse-loadgen/README.md, synse-loadgen/values.yaml
This PR:
- bumps image to 1.0.0
- promotes chart to 1.0.0
=> [synse-loadgen] bump app and chart to 1.0.0

emulator/Chart.yaml, emulator/README.md, emulator/values.yaml
This PR:
- bumps emulator image to 3.0.0
- promotes chart to 3.0.0
=> [emulator] bump app and chart to 3.0.0

synse-server/Chart.yaml, synse-server/README.md, synse-server/values.yaml
This PR:
- bumps synse server app to 3.0.1
- bumps chart to 3.0.1
=> [synse-server] bump app to v3.0.1

synse-server/Chart.yaml, synse-server/README.md, synse-server/values.yaml
https://github.com/vapor-ware/synse-server/releases/tag/v3.0.2
=> [synse-server] bump chart to 3.0.2, app version to 3.0.2

openconfig/Chart.yaml, openconfig/README.md, openconfig/values.yaml
https://github.com/vapor-ware/synse-openconfig-plugin/releases/tag/0.1.1
=> [openconfig] bump app version to 0.1.1

modbus/Chart.yaml, modbus/values.yaml
For https://github.com/vapor-ware/edge-ops/pull/143/files
=> Bump modbus image for read only coils.

modbus/Chart.yaml, modbus/values.yaml
Pick this up for tracing around duplicate device ids under modbus.
=> [modbus] pick up 2.0.4 image

modbus/Chart.yaml, modbus/values.yaml
Picks up https://github.com/vapor-ware/synse-modbus-ip-plugin/pull/59
=> [modbus] 2.0.5 image.

modbus/Chart.yaml, modbus/values.yaml
Pick up https://github.com/vapor-ware/synse-modbus-ip-plugin/pull/63
=> [modbus] 2.0.6 image.

modbus/Chart.yaml, modbus/values.yaml
Pick up https://github.com/vapor-ware/synse-modbus-ip-plugin/pull/65
=> [modbus] 2.0.7 image

modbus/Chart.yaml, modbus/values.yaml
Picks up https://github.com/vapor-ware/synse-modbus-ip-plugin/pull/67
=> [modbus] 2.0.8 image

snmp/Chart.yaml, snmp/values.yaml
Picks up https://github.com/vapor-ware/synse-snmp-plugin/pull/56
=> [snmp] image 2.0.1

synse-server/Chart.yaml, synse-server/README.md, synse-server/values.yaml
https://github.com/vapor-ware/synse-server/releases/tag/v3.1.0
=> [synse-server] update synse-server application version to 3.1.0

.jenkins
Not sure if I did this right, just followed the pattern for what was being done in vapor-charts.
=> ci: update ci pipeline to use helm3

.jenkins
=> ci: update jenkins config to use new chartPublishPipeline

openconfig/Chart.yaml, openconfig/templates/deployment.yaml
=> [openconfig] add deployment annotation for secret sha to roll on secret change

prophetess/.helmignore, prophetess/Chart.yaml, prophetess/_test_values.yaml, prophetess/templates/NOTES.txt, prophetess/templates/_helpers.tpl, prophetess/templates/deployment.yaml, prophetess/templates/ingress.yaml, prophetess/templates/podsecuritypolicy.yaml, prophetess/templates/secret.yaml, prophetess/templates/service.yaml, prophetess/templates/serviceaccount.yaml, prophetess/values.yaml
=> [prophetess] update chart to latest best practices

snmp/Chart.yaml
Depends on: https://github.com/vapor-ware/synse-snmp-plugin/pull/68 and making the tag / image.
=> [snmp] Pick up fix for https://vaporio.atlassian.net/browse/VIO-1089

synse-server/Chart.yaml
Pick up fix for https://vaporio.atlassian.net/browse/VIO-1278
This is the easy part. Related PRs coming.
Currently deployed and tested at:
KE1-ORD (chamber)
KE2-ORD (chamber)
KE3-ORD (chamber)
KE3-PIT (vem150a2)
KE2-PIT (vem180a1)
=> [synse-server] version 3.3.0

modbus/Chart.yaml
Part of https://vaporio.atlassian.net/browse/VIO-1262
Related PRs coming.
=> [modbus] pick up image 2.1.4

modbus/Chart.yaml, modbus/README.md
=> [modbus] Pick up latest synse sdk.

snmp/Chart.yaml, snmp/README.md
=> [snmp] Pick up latest sdk.

openconfig/Chart.yaml, openconfig/README.md
=> [openconfig] Pick up latest sdk.

openconfig/Chart.yaml
Double check if i missed anything, I expected to have to update the readme as wel but didnt find 0.3.2 in there. :shrug:
=> openconfig-plugin - Rev to 0.3.3

snmp/Chart.yaml
https://github.com/vapor-ware/synse-snmp-plugin/releases/tag/2.2.5
https://hub.docker.com/repository/docker/vaporio/snmp-plugin
=> [snmp] Bump to image 2.2.5
