- modbus/Chart.yaml
- modbus/values.yaml
The modbus-ip plugin was recently bumped to version 1.1.0 -- this PR updates the helm chart to use that version.
> [modbus] freeze image version at 1.1.0, bump chart version

- synse-server/Chart.yaml
- synse-server/templates/clusterrole.yaml
- synse-server/templates/clusterrolebinding.yaml
- synse-server/templates/deployment.yaml
- synse-server/templates/serviceaccount.yaml
fixes #5 
Tested this on Austin running only Synse Server and some plugins. Without these changes, I saw the permissions failure. With these changes, plugin discovery completed successfully and there were no errors in the logs.
> [synse server] create cluster permissions for plugin discovery

- synse-server/Chart.yaml
- synse-server/templates/configmap.yaml
- synse-server/templates/deployment.yaml
- synse-server/templates/ingress.yaml
- synse-server/templates/service.yaml
- synse-server/values.yaml
This keeps current functionality. However, if you `Values.ingress.hostname` is set it will switch to vhost routing
> [synse-server] Allow for ingress hostname to be configured

- synse-server/Chart.yaml
- synse-server/templates/ingress.yaml
- synse-server/values.yaml
- Helm chart values are additive, so if you specify a label/annotation
it'll hand it down into the values.yaml, making it impossible to delete
a default that is a list/object type.
- Move the onus of configuration to the values.yaml provided by the
operator
- Add TLS annotations
- Fix a bug where values.yaml ingress annotations were not being handed
down
- Various chomps on various things because formatting yaml from a
mustache template is legit hard.
> [Synse Server] - Add TLS to ingress and defaults

- synse-server/Chart.yaml
- synse-server/templates/deployment.yaml
- synse-server/values.yaml
- Synse-server supports configuration via env but the chart template
exposes no means to configure the env of a deployed synse-server. This
chart modification grants a direct YAML env block for passthrough in the
template.
> [synse-server] Adds env passthrough

- emulator/Chart.yaml
- emulator/templates/deployment.yaml
- Adding the configmap hash to deployment, so when we apply a config
change the emulator will rollout the change autonomously vs requiring a
bounce of the pods manually.
> [emulator] - Embed the configmap hash to trigger pod rollout

- emulator/Chart.yaml
- emulator/templates/deployment.yaml
- I errantly placed this in the deployment metadata, not the podspec
metadata during the initial pr. This fixes the bug introduced in: #20
> [emulator] - Move configmap hash to podspec template

- emulator/Chart.yaml
- emulator/values.yaml
- Synse Emulator Plugin as of 2.4.3 uses device.GUID instead of
device.ID to identify devices, which serializes
location,rack,device-id for the devices.
> [synse-emulator-plugin] - Support globally unique device GUID

- emulator/Chart.yaml
- emulator/values.yaml
- Technically should be 2.5.0 but i botched a release increment. I
digress: contains the deprecation of state in favor of status for lock
devices.
Hand in hand with: https://github.com/vapor-ware/management-api/pull/68
and
https://github.com/vapor-ware/synse-emulator-plugin/pull/47
> [synse-emulator-plugin] - Release 2.4.4

- emulator/Chart.yaml
- emulator/values.yaml
- Adds support for declaring/consuming Voltage devices
- Adds support for declaring/consuming KilowattHour devices
- Bumps chart rev 0.2.10
- bumps default image to 2.5.0
> [synse-emulator] - Adds Voltage and Kilowatthour devices

- emulator/Chart.yaml
- emulator/values.yaml
- Release a patch for current device labels
- bumps to 2.5.2 of the emulator
- bumps chart to 0.2.12
> [synse-emulator-plugin] emulator 2.5.2

- emulator/Chart.yaml
- emulator/values.yaml
- 2.5.2 was a broken image. 2.5.3 corrects the "current" device readings
which were incorrectly searching for "amperage" output types.
> [synse-emulator] - Default to 2.5.3

- synse-server/Chart.yaml
- synse-server/templates/clusterrole.yaml
- synse-server/templates/clusterrolebinding.yaml
- synse-server/templates/deployment.yaml
- synse-server/templates/serviceaccount.yaml
- synse-server/values.yaml
* updates to synse-server v3.0.0-alpha.2 image, which includes minor cleanup and logging changes
* updates the mount path of the configmap to synse-server's v3 default config location
* removes default config specified in values.yaml, since it appears that this was being merged with override config, not replaced by override config.
* adds an explicit config option for enabling cluster roles (+ cluster role binding, + service account) creation. without this, chart linting will fail because we cannot resolve the config discovery value which was present by default before. this means that it is up to the chart user to explicitly enable cluster role creation if synse-server is configured for plugin discovery via the Kubernetes API.
> [synse-server] updates for v3.0.0-alpha.2

- emulator/Chart.yaml
- emulator/README.md
- emulator/templates/NOTES.txt
- emulator/templates/_helpers.tpl
- emulator/templates/configmap.yaml
- emulator/templates/deployment.yaml
- emulator/templates/service.yaml
- emulator/values.yaml
This PR:
- bumps the chart to 3.0.0-alpha.6 and the app version to 3.0.0-alpha.8
- documents configurable values in the README
- general chart updates and cleanup to make things more flexible (e.g. add affinity, tolerations, nodeSelector, etc) and more explicit (e.g. not using template for labels/annotations/selectors, etc).
- reorganizes some of the options in values.yaml 
- updates NOTES.txt to not just wholesale dump the entire values config which everyone ignores, but instead just print out the chart/app version. may or may not be useful, but its not a wall of config that gets ignored anyways.
- cleans up how the configs get mounted in. need to use a subpath for the plugin config so the volume mounting doesn't wipe away the devices dir (see: …
> [emulator] bump app to 3.0.0-alpha.8, general chart updates

- emulator/templates/NOTES.txt
- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/templates/_helpers.tpl
- synse-server/templates/clusterrole.yaml
- synse-server/templates/clusterrolebinding.yaml
- synse-server/templates/configmap.yaml
- synse-server/templates/deployment.yaml
- synse-server/templates/ingress.yaml
- synse-server/templates/service.yaml
- synse-server/templates/serviceaccount.yaml
- synse-server/values.yaml
This PR:
- bumps the chart and image version to [3.0.0-alpha.8](https://github.com/vapor-ware/synse-server/releases/tag/v3.0.0-alpha.8)
- documents the configurable values in the README
- general chart updates and cleanup to make things more flexible (e.g. add affinity, tolerations, nodeSelector, etc) and more explicit (e.g. not using template for labels/annotations/selectors, etc).
- reorganizes some of the options in values.yaml
- changes `clusterRoles` option to `rbac` since it seems more appropriate given the scope of resources it creates.
- updates NOTES.txt to not just wholesale dump the entire values config which everyone ignores, but instead just print out the chart/app version. may or may not be useful, but its not a wall of config that gets ignored anyways.
of note, this also …
> [synse-server] bump to 3.0.0-alpha.8 and general chart updates

- emulator/Chart.yaml
- emulator/README.md
- emulator/values.yaml
This PR:
- bumps the application version to 3.0.0-alpha.9, which expands upon the returned readings for the fan device
> [emulator] bump application version to 3.0.0-alpha.9

- synse-server/Chart.yaml
- synse-server/templates/NOTES.txt
This PR:
- removes the `engine` field in the Chart, since we are just specifying the default
- tidies up the output from NOTES.txt so it is less noisy and perhaps more useful
- bumps the chart version to 3.0.0-alpha.9
> [synse-server] update NOTES.txt to be less noisy

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/values.yaml
This PR:
- bumps the synse-server image version to `v3.0.0-alpha.9`
> [synse-server] bump image version to v3.0.0-alpha.9

- etamay/Chart.yaml
- modbus/Chart.yaml
- snmp/Chart.yaml
This PR:
- adds the `apiVersion` field to Charts which are missing them
fixes #55
> Chart api versions

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/templates/deployment.yaml
- synse-server/values.yaml
This PR:
- bumps the synse-server chart to use the 3.0.0-alpha.10 image
- adds a value configuration for enabling/disabling application metrics export
- sets environment variable based on configured value
This is the same as #54 -- reopened as separate PR because of some weird rebasing issues
> [synse-server] add option to enable/disable application metrics export

- emulator/Chart.yaml
- emulator/README.md
- emulator/templates/deployment.yaml
- emulator/templates/service.yaml
- emulator/values.yaml
This PR:
- bumps the chart to 3.0.0-alpha.8
- bumps the image version to 3.0.0-alpha.10
- adds config for enabling/disabling metrics export via prometheus (`:2112/metrics`)
> [emulator] add option to enable/disable application metrics export

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/values.yaml
This PR:
- bumps the synse server image version to 3.0.0-alpha.11, bringing updates to application metrics
> [synse-server] bump application to v3.0.0-alpha.11

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/values.yaml
This PR:
- bumps the version of synse server to `3.0.0-alpha.12` which includes a bugfix for metrics collection on streamed responses
> [synse-server] bump app version to 3.0.0-alpha.12

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/values.yaml
This PR:
- bumps the version of synse server to 3.0.0-alpha.13
> [synse-server] bump application to v3.0.0-alpha.13

- snmp/Chart.yaml
- snmp/templates/deployment.yaml
This will make sure that if we change SNMP configuration that the pods will re-cycle to get the changes
> [snmp] re-cycle deployments when configmap changes

- modbus/Chart.yaml
- modbus/README.md
- modbus/templates/NOTES.txt
- modbus/templates/_helpers.tpl
- modbus/templates/configmap.yaml
- modbus/templates/deployment.yaml
- modbus/templates/service.yaml
- modbus/values.yaml
This PR:
- updates the modbus chart definitions, allowing it to be more flexible/configurable and better documented
~Some of the changes here are specific for the v3 version of the modbus image, so I'm opening this as a draft for initial review. Once v3 lands, this PR can be converted into a regular PR.~
https://github.com/vapor-ware/synse-modbus-ip-plugin/releases/tag/3.0.0-alpha.1
> [modbus] chart improvements and updates for v3 plugin

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/values.yaml
This PR:
- bumps the synse-server chart to use application version [v3.0.0-alpha.14](https://github.com/vapor-ware/synse-server/compare/v3.0.0-alpha.13...v3.0.0-alpha.14)
> [synse-server] bump application to v3.0.0-alpha.14

- .jenkins
- move to the new charts.vapor.io gcs bucket/lb pattern
> [charts] - Update backend gcs location for publishing

- modbus/Chart.yaml
- modbus/values.yaml
This PR:
- updates the modbus plugin config to enable the plugin cache by default (locally caches reading values for 5min; this give more context for synse's `/readcache` endpoint)
- bumps chart version to `1.0.1-alpha.1`. I accidentally set the version to `1.0.0` before instead of `1.0.0-alpha.1`, so I just bumped the patch version and added the alpha.
> [modbus] enable plugin cache by default

- synse-server/Chart.yaml
- synse-server/README.md
- synse-server/values.yaml
This PR:
- bumps the version of synse server to 3.0.0
- bumps the chart version to 3.0.0
> [synse-server] bump app to version 3.0.0

- modbus/Chart.yaml
- modbus/README.md
- modbus/values.yaml
This PR:
- bumps the app version to 2.0.0
- bumps the chart version to 2.0.0 -- I'm not sure that it needs to be a major version bump here, but it feels a little weird releasing a new major image version as chart version `1.0.2` or `1.1.0`. However, I'm not married to it, so if there are dissenting opinions, I can change the chart version.
> [modbus] bump app to version 2.0.0

- snmp/Chart.yaml
- snmp/README.md
- snmp/values.yaml
This PR:
- bumps the app version to 2.0.0
- bumps the chart version to 2.0.0 -- I'm not sure that it needs to be a major version bump here, but it feels a little weird releasing a new major image version as chart version `1.0.2` or `1.1.0`. However, I'm not married to it, so if there are dissenting opinions, I can change the chart version.
> [snmp] bump app to 2.0.0

- synse-loadgen/Chart.yaml
- synse-loadgen/README.md
- synse-loadgen/values.yaml
This PR:
- bumps synse-loadgen to 1.0.1
- bumps the chart to 1.0.1
https://github.com/vapor-ware/synse-loadgen/releases/tag/1.0.1
> [synse-loadgen] bump app to version 1.0.1

- snmp-ups/.helmignore
- snmp-ups/Chart.yaml
- snmp-ups/README.md
- snmp-ups/templates/NOTES.txt
- snmp-ups/templates/_helpers.tpl
- snmp-ups/templates/configmap.yaml
- snmp-ups/templates/deployment.yaml
- snmp-ups/templates/service.yaml
- snmp-ups/values.yaml
This PR:
- adds the initial definitions for the synse snmp ups plugin chart
~This is currently a WIP as the plugin work is completed and the correct version is cut. I don't anticipate any changes to the chart in relation to the outstanding work for the plugin.~
> [snmp-ups] initial commit of the snmp-ups chart definition

- emulator/Chart.yaml
- emulator/README.md
- emulator/values.yaml
This PR:
- bumps  the emulator app  version to  3.0.2
- bumps the chart version to 3.0.1
https://github.com/vapor-ware/synse-emulator-plugin/releases/tag/3.0.2
> [emulator] bump app version to 3.0.2

- juniper-jti/.helmignore
- juniper-jti/Chart.yaml
- juniper-jti/README.md
- juniper-jti/templates/NOTES.txt
- juniper-jti/templates/_helpers.tpl
- juniper-jti/templates/configmap.yaml
- juniper-jti/templates/deployment.yaml
- juniper-jti/templates/service.yaml
- juniper-jti/templates/servicemonitor.yaml
- juniper-jti/values.yaml
This PR:
- adds in a Juniper JTI chart to the charts repo
~This  is  still a WIP~, as it depends on:
https://github.com/vapor-ware/synse-juniper-jti-plugin/releases/tag/0.1.0
> [juniper-jti] initial commit of the juniper-jti chart (0.1.0)

- juniper-jti/Chart.yaml
- juniper-jti/README.md
- juniper-jti/templates/NOTES.txt
- juniper-jti/templates/deployment.yaml
- juniper-jti/templates/service.yaml
- juniper-jti/values.yaml
This PR:
- bumps the chart version to 0.1.1
- adds basic support for configuring NodePort service
- update values config to nest JTI udp server port under the `service` block
- renames juniper telemetry udp port from  `udpServer` to `jti`
- updates readme
> [juniper-jti]  add basic support for NodePort service type

- juniper-jti/values.yaml
This PR:
- updates some comments, removing copy-pasted reference to  the emulator plugin and fixing a typo
> [juniper-jti] update comments in values.yaml

- juniper-jti/Chart.yaml
- juniper-jti/README.md
- juniper-jti/values.yaml
https://github.com/vapor-ware/synse-juniper-jti-plugin/releases/tag/0.1.1
> [juniper-jti] bump chart to 0.1.2, app version to 0.1.1

- juniper-jti/Chart.yaml
- juniper-jti/README.md
- juniper-jti/templates/deployment.yaml
- juniper-jti/templates/service.yaml
- juniper-jti/values.yaml
This PR:
-  bumps the chart version to 0.1.3
- splits the service definition to allow setting the JTI UDP port to a load  balancer
- fixed issue where no ClusterIP specified defaulted to None
- update readme
> [juniper-jti] split service definitions, bump chart to 0.1.3

- prophetess/Chart.yaml
- prophetess/values.yaml
This  PR contains app version updates  for the following charts:
- **prophetess**: `0.2.0` --> [`0.2.1`](https://github.com/vapor-ware/prophetess/releases/tag/0.2.1)
> Chart updates for new app versions

- openconfig/.helmignore
- openconfig/Chart.yaml
- openconfig/README.md
- openconfig/templates/NOTES.txt
- openconfig/templates/_helpers.tpl
- openconfig/templates/configmap.yaml
- openconfig/templates/deployment.yaml
- openconfig/templates/service.yaml
- openconfig/templates/servicemonitor.yaml
- openconfig/values.yaml
This PR:
- adds an initial helm chart for the synse-openconfig-plugin v0.1.0 (https://github.com/vapor-ware/synse-openconfig-plugin/releases/tag/0.1.0)
> [openconfig] initial commit of the synse openconfig plugin chart

- openconfig/Chart.yaml
- openconfig/README.md
- openconfig/templates/deployment.yaml
- openconfig/templates/secrets.yaml
- openconfig/values.yaml
This PR:
- bumps the chart version to 0.2.0
- adds config options  for specifying tls key/cert/ca, which get mounted  in as secrets
related: https://github.com/vapor-ware/helmfiles/pull/9#discussion_r447199175
> [openconfig] add support for mounting in tls key/cert/ca as secret

- modbus/Chart.yaml
- modbus/README.md
- modbus/templates/service.yaml
- modbus/templates/servicemonitor.yaml
- modbus/values.yaml
This PR:
- adds a service monitor template for prometheus scrape of application metrics
> [modbus] add template for service monitor

- snmp-ups/Chart.yaml
- snmp-ups/README.md
- snmp-ups/templates/service.yaml
- snmp-ups/templates/servicemonitor.yaml
- snmp-ups/values.yaml
This PR:
- adds a service monitor template for prometheus scrape of application metrics
> [snmp-ups] add template for service monitor

- emulator/Chart.yaml
- emulator/README.md
- emulator/templates/service.yaml
- emulator/templates/servicemonitor.yaml
- emulator/values.yaml
This PR:
- adds a service monitor template for prometheus scrape of application metrics
> [emulator] add template for service monitor

- snmp/Chart.yaml
- snmp/README.md
- snmp/templates/service.yaml
- snmp/templates/servicemonitor.yaml
- snmp/values.yaml
This PR:
- adds a service monitor template for prometheus scrape of application metrics
> [snmp] add template for service monitor

- modbus/Chart.yaml
- modbus/values.yaml
Update image with device id traces from the synse sdk.
Depends on https://github.com/vapor-ware/synse-modbus-ip-plugin/pull/56 and image build.
> [modbus] 2.0.3 image

- etamay/Chart.yaml
- etamay/templates/ingress.yaml
- prophetess/Chart.yaml
- prophetess/templates/ingress.yaml
- synse-server/Chart.yaml
- synse-server/templates/ingress.yaml
- Adding conditionals to make the charts support a kube 1.20+ future
Part of https://github.com/vapor-ware/cloud-ops/issues/647
> Deprecating some API Objects

- emulator/Chart.yaml
- emulator/README.md
- emulator/templates/servicemonitor.yaml
- emulator/values.yaml
- juniper-jti/Chart.yaml
- juniper-jti/README.md
- juniper-jti/templates/servicemonitor.yaml
- juniper-jti/values.yaml
- modbus/Chart.yaml
- modbus/README.md
- modbus/templates/servicemonitor.yaml
- modbus/values.yaml
- openconfig/Chart.yaml
- openconfig/README.md
- openconfig/templates/servicemonitor.yaml
- openconfig/values.yaml
- snmp-ups/Chart.yaml
- snmp-ups/README.md
- snmp-ups/templates/servicemonitor.yaml
- snmp-ups/values.yaml
- snmp/Chart.yaml
- snmp/README.md
- snmp/templates/servicemonitor.yaml
- snmp/values.yaml
- synse-server/README.md
This PR:
- fixes incorrect service monitor names so  that they comply with the DNS RFC
Related to #116
> Update service monitor default names to comply with DNS RFC

- prophetess/Chart.yaml
- prophetess/templates/deployment.yaml
- prophetess/templates/secret.yaml
- The configmap leaked some potentially sensitive details, the config
seems to just embed api details into the file. This moves it to a k8s
secret which has a different security model.
Related to https://github.com/vapor-ware/synse-charts/issues/125
> [prophetess] Update chart to use a secret instead of configmap

- prophetess/Chart.yaml
- prophetess/templates/secret.yaml
This was my mistake when I did the "bare minimum" to convert the
configmap to a secret. Secret values are by default base64 encoded, and
the chart template wasn't helping perform any of that.
1.0.4 fixes 1.0.3
> [prophetess] Update secret to base64 encode the value

- snmp/Chart.yaml
- snmp/README.md
- snmp/values.yaml
This will support the VEM-180 UPS.
In order to merge this, we need:
- This PR to land https://github.com/vapor-ware/synse-snmp-plugin/pull/57
- Cut SNMP image version 2.0.2
> [snmp] Support Galaxy UPS.

- openconfig/Chart.yaml
- openconfig/README.md
- openconfig/values.yaml
Updates the Chart to use v0.2.0 of the OpenConfig plugin. [[changelog]](https://github.com/vapor-ware/synse-openconfig-plugin/releases/tag/v0.2.0)
> [openconfig] update app to v0.2.0

- emulator/Chart.yaml
- emulator/templates/servicemonitor.yaml
- juniper-jti/Chart.yaml
- juniper-jti/templates/servicemonitor.yaml
- modbus/Chart.yaml
- modbus/templates/servicemonitor.yaml
- snmp-ups/Chart.yaml
- snmp-ups/templates/servicemonitor.yaml
- snmp/Chart.yaml
- snmp/templates/servicemonitor.yaml
- synse-server/Chart.yaml
- synse-server/templates/servicemonitor.yaml
This PR:
- updates what I believe is a copy-paste bug in the service monitor template for all affected charts. bumps respective chart versions.
> bugfixes: updates to mis-configured service monitor template

- openconfig/Chart.yaml
- openconfig/templates/NOTES.txt
- openconfig/templates/_helpers.tpl
- openconfig/templates/configmap.yaml
- openconfig/templates/deployment.yaml
- openconfig/templates/hpa.yaml
- openconfig/templates/ingress.yaml
- openconfig/templates/secrets.yaml
- openconfig/templates/service.yaml
- openconfig/templates/serviceaccount.yaml
- openconfig/templates/servicemonitor.yaml
- openconfig/values.yaml
This PR:
- updates the OC plugin helm chart to helmv3
- fixes a bug in how deployment volumes were rendered
- fixes a bug in service monitor selector labels template check
- fixes inconsistent formatting
- simplifies some templating using the `with` keyword
- updates labels to use the generated ones via the helpers.tpl file
The one controversial thing here is:
- removes the `synse-component: plugin` label from chart declaration
This was done because it felt incorrect to just slap that label on as a baked-in value, feels like it should be configurable to whoever is consuming it. I can add back in if thats the consensus, just trying to better differentiate chart vs config.
> Update OpenConfig charts to helmv3 plus other bug fixes

- snmp/Chart.yaml
- snmp/values.yaml
Picks up: https://github.com/vapor-ware/synse-snmp-plugin/pull/63
Paired with:
https://github.com/vapor-ware/edge-ops/pull/262
Need an snmp 2.0.3 release to merge / deploy on the VEM-180 only.
> [snmp] Pick up #61 fix.

- snmp/Chart.yaml
- snmp/values.yaml
Paired with https://github.com/vapor-ware/edge-ops/pull/264
We have a 2.0.4 image https://hub.docker.com/layers/vaporio/snmp-plugin/2.0.4/images/sha256-504bb69121e132b134ca4857e9c6b8dda77f06b7b4a2602216e673aef36160c6?context=repo
> [snmp] 2.0.4 image

- openconfig/Chart.yaml
- openconfig/README.md
- openconfig/templates/deployment.yaml
- openconfig/templates/secrets.yaml
- openconfig/values.yaml
This PR: 
- updates openconfig plugin to [v0.3.0](https://github.com/vapor-ware/synse-openconfig-plugin/releases/tag/v0.3.0), which adds support for loading auth passwords via env
- updates the charts to add a `secrets` list in `values.yaml` which enables you to define the passwords as secrets. these will be loaded into Opaque secrets and those secrets will be mounted into the container as environment variables, matching the name of the secret.
<details>
<summary>Example template output <b>with</b> secrets</summary>
```console
$ helm template .
---
apiVersion: v1
kind: Secret
metadata:
name: my_secret
labels:
helm.sh/chart: openconfig-1.1.0
app.kubernetes.io/name: openconfig
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/version: "v0.3.0"
app.kubernetes.io/managed-by: Helm …
```
> enable password loading as secret, bump app to 0.3.0

- openconfig/Chart.yaml
- openconfig/templates/deployment.yaml
- openconfig/templates/secrets.yaml
This PR:
- fixes a bug where the secret cannot be applied because its name does not adhere to the DNS-1123 spec.
```
Error: Secret "efr1_openconfig_password" is invalid: metadata.name: Invalid value: "efr1_openconfig_password": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
> [openconfig] fix bug where secret name must follow DNS-1123 spec

- openconfig/Chart.yaml
https://github.com/vapor-ware/synse-openconfig-plugin/releases/tag/v0.3.1
> [openconfig] bump app to version 0.3.1

- etamay/Chart.yaml
This PR:
- is the first step in deprecating the etamay chart. a follow up PR will remove it from the repo.
> [etamay] deprecate chart

- emulator/.helmignore
- emulator/Chart.yaml
- emulator/_test_values.yaml
- emulator/templates/NOTES.txt
- emulator/templates/_helpers.tpl
- emulator/templates/configmap.yaml
- emulator/templates/deployment.yaml
- emulator/templates/hpa.yaml
- emulator/templates/ingress.yaml
- emulator/templates/poddisruptionbudget.yaml
- emulator/templates/podsecuritypolicy.yaml
- emulator/templates/service.yaml
- emulator/templates/serviceaccount.yaml
- emulator/templates/servicemonitor.yaml
- emulator/values.yaml
> [emulator] update chart to latest best practices

- juniper-jti/.helmignore
- juniper-jti/Chart.yaml
- juniper-jti/_test_values.yaml
- juniper-jti/templates/NOTES.txt
- juniper-jti/templates/_helpers.tpl
- juniper-jti/templates/configmap.yaml
- juniper-jti/templates/deployment.yaml
- juniper-jti/templates/poddisruptionbudget.yaml
- juniper-jti/templates/podsecuritypolicy.yaml
- juniper-jti/templates/service.yaml
- juniper-jti/templates/serviceaccount.yaml
- juniper-jti/templates/servicemonitor.yaml
- juniper-jti/values.yaml
> [juniper-jti] update chart to latest best practices

- snmp/.helmignore
- snmp/Chart.yaml
- snmp/_test_values.yaml
- snmp/templates/NOTES.txt
- snmp/templates/_helpers.tpl
- snmp/templates/configmap.yaml
- snmp/templates/deployment.yaml
- snmp/templates/poddisruptionbudget.yaml
- snmp/templates/podsecuritypolicy.yaml
- snmp/templates/service.yaml
- snmp/templates/serviceaccount.yaml
- snmp/templates/servicemonitor.yaml
- snmp/values.yaml
> [snmp] update chart to latest best practices

- modbus/.helmignore
- modbus/Chart.yaml
- modbus/_test_values.yaml
- modbus/templates/NOTES.txt
- modbus/templates/_helpers.tpl
- modbus/templates/configmap.yaml
- modbus/templates/deployment.yaml
- modbus/templates/poddisruptionbudget.yaml
- modbus/templates/podsecuritypolicy.yaml
- modbus/templates/service.yaml
- modbus/templates/serviceaccount.yaml
- modbus/templates/servicemonitor.yaml
- modbus/values.yaml
> [modbus] update chart to latest best practices

- synse-loadgen/.helmignore
- synse-loadgen/Chart.yaml
- synse-loadgen/_test_values.yaml
- synse-loadgen/templates/NOTES.txt
- synse-loadgen/templates/_helpers.tpl
- synse-loadgen/templates/configmap.yaml
- synse-loadgen/templates/deployment.yaml
- synse-loadgen/templates/podsecuritypolicy.yaml
- synse-loadgen/templates/serviceaccount.yaml
- synse-loadgen/values.yaml
> [synse-loadgen] update chart to latest best practices

- synse-server/.helmignore
- synse-server/Chart.yaml
- synse-server/_test_values.yaml
- synse-server/templates/NOTES.txt
- synse-server/templates/_helpers.tpl
- synse-server/templates/clusterrole.yaml
- synse-server/templates/clusterrolebinding.yaml
- synse-server/templates/configmap.yaml
- synse-server/templates/deployment.yaml
- synse-server/templates/ingress.yaml
- synse-server/templates/poddisruptionbudget.yaml
- synse-server/templates/podsecuritypolicy.yaml
- synse-server/templates/service.yaml
- synse-server/templates/serviceaccount.yaml
- synse-server/templates/servicemonitor.yaml
- synse-server/values.yaml
> [synse-server] update chart to latest best practices

- snmp-ups/.helmignore
- snmp-ups/Chart.yaml
- snmp-ups/_test_values.yaml
- snmp-ups/templates/NOTES.txt
- snmp-ups/templates/_helpers.tpl
- snmp-ups/templates/configmap.yaml
- snmp-ups/templates/deployment.yaml
- snmp-ups/templates/poddisruptionbudget.yaml
- snmp-ups/templates/podsecuritypolicy.yaml
- snmp-ups/templates/service.yaml
- snmp-ups/templates/serviceaccount.yaml
- snmp-ups/templates/servicemonitor.yaml
- snmp-ups/values.yaml
This PR:
we don't currently use this chart, so I'm not sure if it should be deprecated or not, but figured I would just update it alongside everything else until there is a ruling on this
> [snmp-ups] update chart to latest best practices

- .jenkins
This PR:
- updates the ref for CI to pull in latest changes
> ci: bump ci ref to 1.6.1

- synse-server/Chart.yaml
This PR:
- fixes a bug found by @AdamIsrael where the tag specified in Chart.yaml is invalid because synse-server uses a v-prefix on tag versions, which the declared version was missing.
> [synse-server] fix version tag for synse server (should be prefixed with v)

- modbus/Chart.yaml
- snmp/Chart.yaml
Partial fix for https://vaporio.atlassian.net/browse/VIO-845
Depends on these PRs:
https://github.com/vapor-ware/synse-modbus-ip-plugin/pull/75
https://github.com/vapor-ware/synse-snmp-plugin/pull/66
> Update plugin dependencies to get device_info on reads.

- snmp/Chart.yaml
- snmp/values.yaml
For some reason k8 complains about it.
This is the default anyway.
helmfile diff fixed:
[helmfile-diff.txt](https://github.com/vapor-ware/synse-charts/files/6627307/helmfile-diff.txt)
previous helmfile diff with error:
```
Comparing release=north-side-snmp, chart=synse/snmp
in ./helmfile.yaml: in .helmfiles[7]: in /Users/mhink/src/vapor/edge-ops/sites/pit/ke2-pit/.helmfile/cache/ssh_github_com_vapor-ware_helmfiles_git.ref=snmp-0.0.3/releases/snmp.yaml: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
/usr/local/bin/helm
ARGS:
0: helm (4 bytes)
1: diff (4 bytes)
2: upgrade (7 bytes)
3: --reset-values (14 bytes)
4: --allow-unreleased (18 bytes)
5: north-side-snmp (15 bytes)
6: synse/snmp (10 bytes)
7: --version (9 bytes)
8: 3.1.0 (5 bytes)
9: --namespace (11 bytes)
10: …
```
> [snmp] Remove securityContext privileged false.

- snmp/Chart.yaml
Fixing this before we start supporting new UPSes: https://vaporio.atlassian.net/browse/VIO-1155
> [snmp] pick up image 2.1.5

- snmp/Chart.yaml
Picks up the SNMP image with deviceTags in the configuration so that we can differentiate between the UPSes.
> [snmp] pick up image 2.2.1

- emulator/Chart.yaml
- emulator/templates/service.yaml
Add loadbalancing to the emulator plugin by removing `clusterIP: None` from the `service.yaml` template. This is one step towards opening external access to the emulator via the synse cli.
> [VIO-2709] Add loadbalancing for emulator plugin
